id: avmEventResponder
name: AVM Event Responder
description: AVM Event Responder
resource: repository
disabled: false

configuration:
  resourceManagementConfiguration:
    eventResponderTasks:
      - description: 'ITA06 - If a new issue or PR is opened add the "Needs: Triage :mag:" label'
        if:
          - or:
              - payloadType: Issues
              - payloadType: Pull_Request
          - isAction:
              action: Opened
        then:
          - addLabel:
              label: "Needs: Triage :mag:"
          - addReply:
              reply: |
                > [!IMPORTANT]
                > **The "Needs: Triage :mag:" label must be removed once the triage process is complete!**

                > [!TIP]
                > For additional guidance on how to triage this issue/PR, see the [AVM Issue Triage](https://azure.github.io/Azure-Verified-Modules/help-support/issue-triage/avm-issue-triage/) documentation.

                > [!NOTE]
                > This label was added as per [ITA06](https://azure.github.io/Azure-Verified-Modules/help-support/issue-triage/issue-triage-automation/#ita06).

      - description: 'ITA09 - When #RR is used in an issue, add the "Needs: Author Feedback :ear:" label'
        if:
          - or:
              - payloadType: Pull_Request_Review_Comment
              - payloadType: Issue_Comment
          - commentContains:
              pattern: "#RR"
          - not:
              hasLabel:
                label: "Needs: Author Feedback :ear:"
        then:
          - addLabel:
              label: "Needs: Author Feedback :ear:"
          - addReply:
              reply: |
                > [!NOTE]
                > The "Needs: Author Feedback :ear:" label was added as per [ITA09](https://azure.github.io/Azure-Verified-Modules/help-support/issue-triage/issue-triage-automation/#ita09).

      - description: 'ITA10 - When #wontfix is used in an issue, mark it by using the label of "Status: Won''t Fix :broken_heart:"'
        if:
          - or:
              - payloadType: Pull_Request_Review_Comment
              - payloadType: Issue_Comment
          - commentContains:
              pattern: "#wontfix"
          - not:
              hasLabel:
                label: "Status: Won't Fix :broken_heart:"
        then:
          - addLabel:
              label: "Status: Won't Fix :broken_heart:"
          - closeIssue
          - addReply:
              reply: |
                > [!NOTE]
                > The "Status: Won't Fix :broken_heart:" label was added and the issue was closed as per [ITA10](https://azure.github.io/Azure-Verified-Modules/help-support/issue-triage/issue-triage-automation/#ita10).

      - description: 'ITA11 - When a reply from anyone to an issue occurs, remove the "Needs: Author Feedback :ear:" label and label with "Needs: Attention :wave:"'
        if:
          - or:
              - payloadType: Pull_Request_Review_Comment
              - payloadType: Issue_Comment
          - not:
              isAction:
                action: Closed
          - hasLabel:
              label: "Needs: Author Feedback :ear:"
        then:
          - removeLabel:
              label: "Needs: Author Feedback :ear:"
          - addLabel:
              label: "Needs: Attention :wave:"
          - addReply:
              reply: |
                > [!NOTE]
                > The "Needs: Author Feedback :ear:" label was removed and the "Needs: Attention :wave:" label was added as per [ITA11](https://azure.github.io/Azure-Verified-Modules/help-support/issue-triage/issue-triage-automation/#ita11).

      - description: "ITA12 - Clean email replies on every comment"
        if:
          - payloadType: Issue_Comment
        then:
          - cleanEmailReply

      - description: 'ITA13 - If the language is set to Bicep in the Module proposal, add the "Language: Bicep :muscle:" label on the issue'
        if:
          - payloadType: Issues
          - isAction:
              action: Opened
          - bodyContains:
              pattern: |
                ### Bicep or Terraform?

                Bicep
          - not:
              hasLabel:
                label: "Language: Bicep :muscle:"
        then:
          - addLabel:
              label: "Language: Bicep :muscle:"
          - addReply:
              reply: |
                > [!NOTE]
                > The "Language: Bicep :muscle:" label was added as per [ITA13](https://azure.github.io/Azure-Verified-Modules/help-support/issue-triage/issue-triage-automation/#ita13).

      - description: 'ITA14 - If the language is set to Terraform in the Module proposal, add the "Language: Terraform :globe_with_meridians:" label on the issue'
        if:
          - payloadType: Issues
          - isAction:
              action: Opened
          - bodyContains:
              pattern: |
                ### Bicep or Terraform?

                Terraform
          - not:
              hasLabel:
                label: "Language: Terraform :globe_with_meridians:"
        then:
          - addLabel:
              label: "Language: Terraform :globe_with_meridians:"
          - addReply:
              reply: |
                > [!NOTE]
                > The "Language: Terraform :globe_with_meridians:" label was added as per [ITA14](https://azure.github.io/Azure-Verified-Modules/help-support/issue-triage/issue-triage-automation/#ita14).

      - description: 'ITA15 - remove the "Needs: Triage" label from a PR, if it already has a "Type: XYZ" label added at the time of creating it.'
        if:
          - payloadType: Pull_Request
          - isAction:
              action: Opened
          - or:
              - hasLabel:
                  label: "Type: Bug :bug:"
              - hasLabel:
                  label: "Type: Documentation :page_facing_up:"
              - hasLabel:
                  label: "Type: Duplicate :palms_up_together:"
              - hasLabel:
                  label: "Type: Feature Request :heavy_plus_sign:"
              - hasLabel:
                  label: "Type: Hygiene :broom:"
              - hasLabel:
                  label: "Type: New Module Proposal :bulb:"
              - hasLabel:
                  label: "Type: Question/Feedback :raising_hand:"
              - hasLabel:
                  label: "Type: Security Bug :lock:"
          - isAssignedToSomeone
        then:
          - removeLabel:
              label: "Needs: Triage :mag:"
          - addReply:
              reply: |
                > [!NOTE]
                > The "Needs: Triage :mag:" label was removed as per [ITA15](https://azure.github.io/Azure-Verified-Modules/help-support/issue-triage/issue-triage-automation/#ita15).

      - description: 'ITA16 - Add the "Status: Owners Identified :metal:" label when someone is assigned to a Module Proposal'
        if:
          - payloadType: Issues
          - not:
              isAction:
                action: Closed
          - not:
              hasLabel:
                  label: "Status: Owners Identified :metal:"
          - hasLabel:
              label: "Type: New Module Proposal :bulb:"
          - isAssignedToSomeone
        then:
          - addLabel:
              label: "Status: Owners Identified :metal:"
          - addReply:
              reply: |
                > [!NOTE]
                > The "Status: Owners Identified :metal:" label was added as per [ITA16](https://azure.github.io/Azure-Verified-Modules/help-support/issue-triage/issue-triage-automation/#ita16).
        triggerOnOwnActions: true

      - description: "ITA17 - If the issue author says they want to be the module owner, assign the issue to the author and respond to them."
        if:
          - payloadType: Issues
          - isAction:
              action: Opened
          - bodyContains:
              pattern: |
                ### Do you want to be the owner of this module?

                Yes
        then:
          - assignTo:
              author: true
          - addReply:
              reply: |
                @${issueAuthor}, thanks for volunteering to be a module owner!

                > [!IMPORTANT]
                > **Please don't start the development just yet!**
                >
                > The AVM core team will review this module proposal and respond to you first. Thank you!

                > [!NOTE]
                > This message was posted as per [ITA17](https://azure.github.io/Azure-Verified-Modules/help-support/issue-triage/issue-triage-automation/#ita17).

      - description: 'ITA18 - Send automatic response to the issue author if they don''t want to be module owner and don''t have any candidate in mind. Add the "Needs: Module Owner :mega:" label.'
        if:
          - payloadType: Issues
          - isAction:
              action: Opened
          - bodyContains:
              pattern: |
                ### Do you want to be the owner of this module?

                No

                ### Module Owner's GitHub Username (handle)

                _No response_
        then:
          - addLabel:
              label: "Needs: Module Owner :mega:"
          - addReply:
              reply: |
                **@${issueAuthor}, thanks for submitting this module proposal!**

                > [!IMPORTANT]
                > The AVM core team will review it and will try to find a module owner.

                > [!NOTE]
                > This message was posted as per [ITA18](https://azure.github.io/Azure-Verified-Modules/help-support/issue-triage/issue-triage-automation/#ita18).

      - description: 'ITA19 - Send automatic response to the issue author if they don''t want to be module owner but have a candidate in mind. Add the "Status: Owners Identified :metal:" label.'
        if:
          - payloadType: Issues
          - isAction:
              action: Opened
          - bodyContains:
              pattern: |
                ### Do you want to be the owner of this module?

                No
          - not:
              bodyContains:
                pattern: |
                  ### Module Owner's GitHub Username (handle)

                  _No response_
        then:
          - addLabel:
              label: "Status: Owners Identified :metal:"
          - addReply:
              reply: |
                **@${issueAuthor}, thanks for submitting this module proposal with a module owner in mind!**

                > [!IMPORTANT]
                > **Please don't start the development just yet!**
                >
                > The AVM core team will review this module proposal and respond to you and/or the module owner first. Thank you!

                > [!NOTE]
                > This message was posted as per [ITA19](https://azure.github.io/Azure-Verified-Modules/help-support/issue-triage/issue-triage-automation/#ita19).

      - description: 'ITA23 - Remove the "Status: In PR" label from an issue when it''s closed.'
        if:
          - payloadType: Issues
          - isAction:
              action: Closed
          - hasLabel:
              label: "Status: In PR :point_right:"
        then:
          - removeLabel:
              label: "Status: In PR :point_right:"
          - addReply:
              reply: |
                > [!NOTE]
                > The "Status: In PR :point_right:" label was removed as per [ITA23](https://azure.github.io/Azure-Verified-Modules/help-support/issue-triage/issue-triage-automation/#ita23).
