id: avmEventResponder
name: AVM Event Responder
description: AVM Event Responder
resource: repository
disabled: false

configuration:
  resourceManagementConfiguration:
    eventResponderTasks:
      - description: ITA09 - If a new issue is opened add the needs triage label
        if:
          - payloadType: Issues
          - and:
            - isAction:
                action: Opened
        then:
          - addLabel:
              label: 'Needs: Triage :mag:'

      - description: ITA10 - If a new pull request is opened add the needs triage label
        if:
          - payloadType: Pull_Request
          - and:
            - isAction:
                action: Opened
        then:
          - addLabel:
              label: 'Needs: Triage :mag:'
