id: avmScheduledSearches
name: AVM Scheduled Searches
description: AVM Scheduled Searches
resource: repository
disabled: false

configuration:
  resourceManagementConfiguration:
    scheduledSearches:
      - description: "ITA04 - Label issues that have been marked as requiring author feedback but have not had any activity for 4 days."
        frequencies:
          - hourly:
              hour: 3
        filters:
          - isIssue
          - isOpen
          - hasLabel:
              label: "Needs: Author Feedback :ear:"
          - noActivitySince:
              days: 4
          - isNotLabeledWith:
              label: "Status: No Recent Activity :zzz:"
        actions:
          - addLabel:
              label: "Status: No Recent Activity :zzz:"
          - addReply:
              reply: |
                > [!IMPORTANT]
                > @${issueAuthor}, this issue has been automatically marked as stale because it has been marked as requiring author feedback but has not had any activity for **4 days**. It will be closed if no further activity occurs **within 3 days of this comment**.

                > [!TIP]
                > To prevent further actions to take effect, one of the following conditions must be met:
                >   - The author must respond in a comment within 3 days of this comment.
                >   - The "Status: No Recent Activity :zzz:" label must be removed.
                >   - If applicable, the "Status: Long Term :hourglass_flowing_sand:" or the "Needs: Module Owner :mega:" label must be added.

                > [!NOTE]
                > This message was posted as per [ITA04](https://azure.github.io/Azure-Verified-Modules/help-support/issue-triage/issue-triage-automation/#ita04).

      - description: 'ITA05A - Close issues that have been marked as requiring author feedback but have not had any activity for 3 days, unless it''s been marked with the "Status long term" label.'
        frequencies:
          - hourly:
              hour: 3
        filters:
          - isIssue
          - isOpen
          - hasLabel:
              label: "Needs: Author Feedback :ear:"
          - hasLabel:
              label: "Status: No Recent Activity :zzz:"
          - isNotLabeledWith:
              label: "Needs: Module Owner :mega:"
          - noActivitySince:
              days: 3
        actions:
          - addReply:
              reply: |
                > [!WARNING]
                > @${issueAuthor}, this issue will now be closed, as it has been marked as requiring author feedback but has not had any activity for **7 days**.

                > [!TIP]
                > In case this issue needs to be reopened (e.g., the author responds after the issue was closed), the "Status: No Recent Activity :zzz:" label must be removed.

                > [!NOTE]
                > This message was posted as per [ITA05](https://azure.github.io/Azure-Verified-Modules/help-support/issue-triage/issue-triage-automation/#ita05).
          - closeIssue

      - description: 'ITA05B - Close issues that have been marked as requiring author feedback but have not had any activity for 3 days, unless it''s been marked with the "Status long term" label.'
        frequencies:
          - hourly:
              hour: 3
        filters:
          - isIssue
          - isOpen
          - hasLabel:
              label: "Needs: Author Feedback :ear:"
          - hasLabel:
              label: "Status: No Recent Activity :zzz:"
          - isNotLabeledWith:
              label: "Status: Long Term :hourglass_flowing_sand:"
          - noActivitySince:
              days: 3
        actions:
          - addReply:
              reply: |
                > [!WARNING]
                > @${issueAuthor}, this issue will now be closed, as it has been marked as requiring author feedback but has not had any activity for **7 days**.

                > [!TIP]
                > In case this issue needs to be reopened (e.g., the author responds after the issue was closed), the "Status: No Recent Activity :zzz:" label must be removed.

                > [!NOTE]
                > This message was posted as per [ITA05](https://azure.github.io/Azure-Verified-Modules/help-support/issue-triage/issue-triage-automation/#ita05).
          - closeIssue

      - description: 'ITA24 - Remind module owner(s) to start or continue working on this module if there was no activity on the Module Proposal issue for more than 3 weeks. "Add Needs: Attention :wave:" label.'
        frequencies:
          - hourly:
              hour: 3
        filters:
          - isIssue
          - isOpen
          - hasLabel:
              label: "Type: New Module Proposal :bulb:"
          - hasLabel:
              label: "Status: Owners Identified :metal:"
          - noActivitySince:
              days: 21
          - isNotLabeledWith:
              label: "Status: Long Term :hourglass_flowing_sand:"
        actions:
          - addReply:
              reply: |
                > [!IMPORTANT]
                > ${assignees}, this issue has not had any activity in the last **3 weeks**. Please feel free to reach out to the AVM core team should you have any questions or need any help with the development of this module.

                > [!TIP]
                > To silence this notification, provide an update every 3 weeks on the Module Proposal issue, or add the "Status: Long Term :hourglass_flowing_sand:" label.

                > [!NOTE]
                > This message was posted as per [ITA24](https://azure.github.io/Azure-Verified-Modules/help-support/issue-triage/issue-triage-automation/#ita24).
          - addLabel:
              label: "Needs: Attention :wave:"
