id: avmScheduledSearches
name: AVM Scheduled Searches
description: AVM Scheduled Searches
resource: repository
disabled: false

configuration:
  resourceManagementConfiguration:
    scheduledSearches:
    - description: ITA04 - Label issues that have been marked as requiring author feedback but have not had any activity for 4 days.
      frequencies:
      - hourly:
          hour: 3
      filters:
      - isIssue
      - isOpen
      - hasLabel:
          label: 'Needs: Author Feedback :ear:'
      - noActivitySince:
          days: 4
      - isNotLabeledWith:
          label: 'Status: No Recent Activity :zzz:'
      actions:
      - addLabel:
          label: 'Status: No Recent Activity :zzz:'
      - addReply:
          reply: |
            @${issueAuthor}, this issue has been automatically marked as stale because it has been marked as requiring author feedback but has not had any activity for **4 days**. It will be closed if no further activity occurs **within 3 days of this comment**.

    - description: ITA05 - Close issues that have been marked as requiring author feedback but have not had any activity for 3 days.
      frequencies:
      - hourly:
          hour: 3
      filters:
      - isIssue
      - isOpen
      - hasLabel:
          label: 'Needs: Author Feedback :ear:'
      - hasLabel:
          label: 'Status: No Recent Activity :zzz:'
      - isNotLabeledWith:
          label: 'Status: Long Term :hourglass_flowing_sand:'
      - isNotLabeledWith:
          label: 'Needs: Module Owner :mega:'
      - noActivitySince:
          days: 3
      actions:
      - addReply:
          reply: |
            @${issueAuthor}, this issue will now be closed, as it has been marked as requiring author feedback but has not had any activity for **7 days**.
      - closeIssue
