name: General Question/Feedback ❔
description: Just got a question or some general feedback? Let us know!
title: "[Question/Feedback]: "
labels: ["Type: Question/Feedback :raising_hand:", "Needs: Triage :mag:"]
projects: ["Azure/538"]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for your question/feedback
  - type: checkboxes
    id: existing-checks
    attributes:
      label: Check for previous/existing GitHub issues
      description: By submitting this issue, you confirm that you have [searched for previous/existing GitHub issues](https://github.com/Azure/Azure-Verified-Modules/issues?q=is%3Aissue+sort%3Aupdated-desc+) to avoid creating a duplicate.
      options:
        - label: I have checked for previous/existing GitHub issues
          required: true
  - type: textarea
    id: question-feedback-text
    attributes:
      label: Description
      description: Let us know your question or feedback here
    validations:
      required: true
