---
###########################
###########################
## Markdown Linter rules ##
###########################
###########################

# Linter rules doc:
# - https://github.com/DavidAnson/markdownlint
#
# Note:
# To comment out a single error:
#   <!-- markdownlint-disable -->
#   any violations you want
#   <!-- markdownlint-restore -->
#

###############
# Rules by id #
###############
MD004: false                  # Unordered list style
MD007:
  indent: 2                   # Unordered list indentation
MD013:
  line_length: 1000            # Line length 80 is far to short
MD026:
  punctuation: ".,;:!。，；:"  # List of not allowed
MD029: false                  # Ordered list item prefix
MD033: false                  # Allow inline HTML
MD036: false                  # Emphasis used instead of a heading
MD053: false                  # Super Linter broke this in v4.9.5
MD024: false                  # Allow multiple headings with same content
MD037: false                  # Allow spaces inside emphasis markers
MD041: false                  # Don't enforce top-level heading in first line
MD046: false                  # Allow hugo styling of codeblocks

#################
# Rules by tags #
#################
blank_lines: false  # Error on blank lines
