<#
.SYNOPSIS
Creates a branch, commits the given files, opens a pull request and merges it.

.DESCRIPTION
Generic helper used by automation workflows that regenerate tracked files in
the repository and need to publish the result via an auto-merged pull request.

Behaviour:
  * Detects working-tree changes for the supplied file paths using
    `git status --porcelain` (this captures both modified and untracked files,
    which matters on the first run when the file does not yet exist on the
    base branch).
  * If no changes are detected the function returns `$null` and exits without
    creating a branch.
  * If changes are detected it creates a timestamped branch under the supplied
    prefix, commits the listed files, pushes the branch, opens a pull request
    via the `gh` CLI and merges it.
  * The PR body may contain a placeholder token (default `{{CHANGED_FILES}}`)
    which is replaced with a markdown bullet list of the files that actually
    changed in this run.

Prerequisites:
  * `git` and `gh` CLI must be on PATH.
  * `GH_TOKEN` (or an authenticated `gh` CLI session) must be available with
    permission to push the branch and create / merge the PR.
  * `git` must be pre-configured with `user.name` and `user.email`.

.PARAMETER FilePath
Required. One or more repository-relative file paths to inspect and (if
changed) commit. The function will only stage these specific paths.

.PARAMETER BranchPrefix
Required. The branch name prefix. A UTC timestamp (`yyyyMMddHHmmss`) is
appended, e.g. `update-module-indexes-json/20260610T120000Z`.

.PARAMETER Title
Required. Pull request title (also used as the commit message, with the
timestamp appended).

.PARAMETER Body
Required. Pull request body. May contain `{{CHANGED_FILES}}` (or the value of
`-ChangedFilesPlaceholder`) which will be replaced with a markdown bullet list
of the files included in the commit.

.PARAMETER ChangedFilesPlaceholder
Optional. The token in `-Body` to replace with the list of changed files.
Defaults to `{{CHANGED_FILES}}`. If the token is not present in `-Body` the
body is sent unchanged.

.PARAMETER BaseRef
Optional. The branch to target with the PR. Defaults to `$env:GITHUB_REF_NAME`
when run inside GitHub Actions.

.PARAMETER Repository
Optional. The `owner/repo` slug. Defaults to `$env:GITHUB_REPOSITORY` when run
inside GitHub Actions.

.PARAMETER MergeMethod
Optional. One of `merge`, `squash`, `rebase`. Defaults to `squash`.

.PARAMETER Admin
Optional. When set, passes `--admin` to `gh pr merge` so the PR is merged
immediately, bypassing branch-protection rules. Requires the executing
identity (typically a GitHub App) to have admin rights on the repository.
When not set the function passes `--auto` instead, letting GitHub merge the
PR once the required status checks pass.

.OUTPUTS
[string] The URL of the merged pull request, or `$null` if no changes were
detected.

.EXAMPLE
New-AutoMergePullRequest `
    -FilePath @('docs/static/module-indexes/modules.json',
                'docs/static/module-indexes/bicep.json',
                'docs/static/module-indexes/terraform.json') `
    -BranchPrefix 'update-module-indexes-json' `
    -Title       'Update module indexes JSON (automated)' `
    -Body        "Regenerated by the platform workflow.`n`nFiles updated:`n{{CHANGED_FILES}}" `
    -Admin
#>
function New-AutoMergePullRequest {

    [CmdletBinding(SupportsShouldProcess)]
    [OutputType([string])]
    param (
        [Parameter(Mandatory = $true)]
        [string[]] $FilePath,

        [Parameter(Mandatory = $true)]
        [string] $BranchPrefix,

        [Parameter(Mandatory = $true)]
        [string] $Title,

        [Parameter(Mandatory = $true)]
        [string] $Body,

        [Parameter(Mandatory = $false)]
        [string] $ChangedFilesPlaceholder = '{{CHANGED_FILES}}',

        [Parameter(Mandatory = $false)]
        [string] $BaseRef = $env:GITHUB_REF_NAME,

        [Parameter(Mandatory = $false)]
        [string] $Repository = $env:GITHUB_REPOSITORY,

        [Parameter(Mandatory = $false)]
        [ValidateSet('merge', 'squash', 'rebase')]
        [string] $MergeMethod = 'squash',

        [Parameter(Mandatory = $false)]
        [switch] $Admin
    )

    if ([string]::IsNullOrWhiteSpace($BaseRef)) {
        throw 'BaseRef was not supplied and the GITHUB_REF_NAME environment variable is empty.'
    }
    if ([string]::IsNullOrWhiteSpace($Repository)) {
        throw 'Repository was not supplied and the GITHUB_REPOSITORY environment variable is empty.'
    }

    # Detect working-tree changes for the supplied paths. `git status --porcelain`
    # returns lines like ' M path/to/file' or '?? path/to/file' (untracked).
    $statusLines = git status --porcelain -- $FilePath | Where-Object { $_ }
    if (-not $statusLines) {
        Write-Host 'No changes detected. Exiting.'
        return $null
    }

    # Extract the actual file paths from the porcelain output (strip the 2-char
    # status prefix and the following space) so we can present them in the body.
    $changedFiles = $statusLines | ForEach-Object { $_.Substring(3).Trim() } | Sort-Object -Unique
    Write-Host ('Detected {0} changed file(s):' -f $changedFiles.Count)
    $changedFiles | ForEach-Object { Write-Host "  $_" }

    $dateStamp  = (Get-Date).ToUniversalTime().ToString('yyyyMMddTHHmmssZ')
    $branchName = "$BranchPrefix/$dateStamp"

    if (-not $PSCmdlet.ShouldProcess($branchName, 'Create branch, commit, push, open PR and merge')) {
        return $null
    }

    # Build the final PR body, substituting the changed-files list if requested.
    $finalBody = $Body
    if ($Body.Contains($ChangedFilesPlaceholder)) {
        $changedFilesMarkdown = ($changedFiles | ForEach-Object { "- ``$_``" }) -join "`n"
        $finalBody = $Body.Replace($ChangedFilesPlaceholder, $changedFilesMarkdown)
    }

    git checkout -b $branchName
    if ($LASTEXITCODE -ne 0) { throw "git checkout -b $branchName failed (exit $LASTEXITCODE)." }

    git add -- $FilePath
    if ($LASTEXITCODE -ne 0) { throw "git add failed (exit $LASTEXITCODE)." }

    git commit -m "$Title ($dateStamp)"
    if ($LASTEXITCODE -ne 0) { throw "git commit failed (exit $LASTEXITCODE)." }

    gh auth setup-git
    if ($LASTEXITCODE -ne 0) { throw "gh auth setup-git failed (exit $LASTEXITCODE)." }

    git push --set-upstream origin $branchName
    if ($LASTEXITCODE -ne 0) { throw "git push failed (exit $LASTEXITCODE)." }

    $prUrl = gh pr create `
        --title $Title `
        --body  $finalBody `
        --base  $BaseRef `
        --head  $branchName `
        --repo  $Repository
    if ($LASTEXITCODE -ne 0 -or [string]::IsNullOrWhiteSpace($prUrl)) {
        throw "gh pr create failed (exit $LASTEXITCODE)."
    }
    Write-Host "Created PR: $prUrl"

    $mergeArgs = @('pr', 'merge', $prUrl, "--$MergeMethod", '--delete-branch')
    $mergeArgs += if ($Admin.IsPresent) { '--admin' } else { '--auto' }
    & gh @mergeArgs
    if ($LASTEXITCODE -ne 0) { throw "gh pr merge failed (exit $LASTEXITCODE)." }
    Write-Host "Merged PR: $prUrl"

    return $prUrl
}
