# Workflow for testing all module index CSVs
name: .Platform - Test Module Index CSVs

on:
  pull_request:
    paths:
      - 'docs/static/module-indexes/**'
  workflow_dispatch: {}

defaults:
  run:
    shell: pwsh

jobs:
  Test-Module-Index-CSVs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Test All Bicep and Terraform Module Index CSVs
        shell: pwsh
        run: |
          $RepoRoot = $env:GITHUB_WORKSPACE

          . (Join-Path $RepoRoot "utilities" "tools" "module-indexes" "Test-AvmModuleIndexCSVs.ps1")
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

